package main

type UserInformation struct {
	Result struct {
		User struct {
			HasAnonymousProfilePicture                   bool `json:"has_anonymous_profile_picture"`
			IsSupervisionFeaturesEnabled                 bool `json:"is_supervision_features_enabled"`
			FollowerCount                                int  `json:"follower_count"`
			MediaCount                                   int  `json:"media_count"`
			FollowingCount                               int  `json:"following_count"`
			FollowingTagCount                            int  `json:"following_tag_count"`
			CanUseAffiliatePartnershipMessagingAsCreator bool `json:"can_use_affiliate_partnership_messaging_as_creator"`
			CanUseAffiliatePartnershipMessagingAsBrand   bool `json:"can_use_affiliate_partnership_messaging_as_brand"`
			HasPrivateCollections                        bool `json:"has_private_collections"`
			ShowAccountTransparencyDetails               bool `json:"show_account_transparency_details"`
			HasMusicOnProfile                            bool `json:"has_music_on_profile"`
			IsPotentialBusiness                          bool `json:"is_potential_business"`
			HasNftPosts                                  bool `json:"has_nft_posts"`
			CanUseBrandedContentDiscoveryAsCreator       bool `json:"can_use_branded_content_discovery_as_creator"`
			CanUseBrandedContentDiscoveryAsBrand         bool `json:"can_use_branded_content_discovery_as_brand"`
			FanClubInfo                                  struct {
				FanClubID                            any `json:"fan_club_id"`
				FanClubName                          any `json:"fan_club_name"`
				IsFanClubReferralEligible            any `json:"is_fan_club_referral_eligible"`
				FanConsiderationPageRevampEligiblity any `json:"fan_consideration_page_revamp_eligiblity"`
				IsFanClubGiftingEligible             any `json:"is_fan_club_gifting_eligible"`
			} `json:"fan_club_info"`
			Pronouns                                  []any  `json:"pronouns"`
			WhatsappNumber                            string `json:"whatsapp_number"`
			IsWhatsappLinked                          bool   `json:"is_whatsapp_linked"`
			TransparencyProductEnabled                bool   `json:"transparency_product_enabled"`
			IsFacebookOnboardedCharity                bool   `json:"is_facebook_onboarded_charity"`
			HasActiveCharityBusinessProfileFundraiser bool   `json:"has_active_charity_business_profile_fundraiser"`
			CharityProfileFundraiserInfo              struct {
				Pk                         string `json:"pk"`
				IsFacebookOnboardedCharity bool   `json:"is_facebook_onboarded_charity"`
				HasActiveFundraiser        bool   `json:"has_active_fundraiser"`
				ConsumptionSheetConfig     struct {
					CanViewerDonate         bool   `json:"can_viewer_donate"`
					Currency                any    `json:"currency"`
					DonationURL             any    `json:"donation_url"`
					PrivacyDisclaimer       any    `json:"privacy_disclaimer"`
					DonationDisabledMessage string `json:"donation_disabled_message"`
					DonationAmountConfig    struct {
						DonationAmountSelectorValues []any `json:"donation_amount_selector_values"`
						DefaultSelectedDonationValue any   `json:"default_selected_donation_value"`
						MinimumDonationAmount        any   `json:"minimum_donation_amount"`
						MaximumDonationAmount        any   `json:"maximum_donation_amount"`
						PrefillAmount                any   `json:"prefill_amount"`
						UserCurrency                 any   `json:"user_currency"`
					} `json:"donation_amount_config"`
					YouDonatedMessage   any `json:"you_donated_message"`
					ProfileFundraiserID any `json:"profile_fundraiser_id"`
					HasViewerDonated    any `json:"has_viewer_donated"`
				} `json:"consumption_sheet_config"`
			} `json:"charity_profile_fundraiser_info"`
			InteropMessagingUserFbid int64 `json:"interop_messaging_user_fbid"`
			BioLinks                 []struct {
				LinkID                          string `json:"link_id"`
				URL                             string `json:"url"`
				LynxURL                         string `json:"lynx_url"`
				LinkType                        string `json:"link_type"`
				Title                           string `json:"title"`
				OpenExternalURLWithInAppBrowser bool   `json:"open_external_url_with_in_app_browser"`
			} `json:"bio_links"`
			CanAddFbGroupLinkOnProfile bool   `json:"can_add_fb_group_link_on_profile"`
			ExternalURL                string `json:"external_url"`
			ExternalLynxURL            string `json:"external_lynx_url"`
			ShowShoppableFeed          bool   `json:"show_shoppable_feed"`
			ShoppablePostsCount        int    `json:"shoppable_posts_count"`
			MerchantCheckoutStyle      string `json:"merchant_checkout_style"`
			SellerShoppableFeedType    string `json:"seller_shoppable_feed_type"`
			HasActiveAffiliateShop     bool   `json:"has_active_affiliate_shop"`
			CreatorShoppingInfo        struct {
				LinkedMerchantAccounts []any `json:"linked_merchant_accounts"`
			} `json:"creator_shopping_info"`
			HasGuides           bool `json:"has_guides"`
			HasHighlightReels   bool `json:"has_highlight_reels"`
			HdProfilePicURLInfo struct {
				URL          string `json:"url"`
				Width        int    `json:"width"`
				Height       int    `json:"height"`
				URLSignature struct {
					Expires   int    `json:"expires"`
					Signature string `json:"signature"`
				} `json:"url_signature"`
			} `json:"hd_profile_pic_url_info"`
			HdProfilePicVersions []struct {
				Width        int    `json:"width"`
				Height       int    `json:"height"`
				URL          string `json:"url"`
				URLSignature struct {
					Expires   int    `json:"expires"`
					Signature string `json:"signature"`
				} `json:"url_signature"`
			} `json:"hd_profile_pic_versions"`
			IsInterestAccount                          bool    `json:"is_interest_account"`
			IsFavorite                                 bool    `json:"is_favorite"`
			UsertagsCount                              int     `json:"usertags_count"`
			TotalArEffects                             int     `json:"total_ar_effects"`
			TotalClipsCount                            int     `json:"total_clips_count"`
			HasVideos                                  bool    `json:"has_videos"`
			TotalIgtvVideos                            int     `json:"total_igtv_videos"`
			Biography                                  string  `json:"biography"`
			IncludeDirectBlacklistStatus               bool    `json:"include_direct_blacklist_status"`
			ShowFbLinkOnProfile                        bool    `json:"show_fb_link_on_profile"`
			PrimaryProfileLinkType                     int     `json:"primary_profile_link_type"`
			HasBiographyTranslation                    bool    `json:"has_biography_translation"`
			CanHideCategory                            bool    `json:"can_hide_category"`
			CanHidePublicContacts                      bool    `json:"can_hide_public_contacts"`
			ShouldShowCategory                         bool    `json:"should_show_category"`
			CategoryID                                 string  `json:"category_id"`
			IsCategoryTappable                         bool    `json:"is_category_tappable"`
			ShouldShowPublicContacts                   bool    `json:"should_show_public_contacts"`
			IsEligibleForSmbSupportFlow                bool    `json:"is_eligible_for_smb_support_flow"`
			IsEligibleForLeadCenter                    bool    `json:"is_eligible_for_lead_center"`
			IsExperiencedAdvertiser                    bool    `json:"is_experienced_advertiser"`
			LeadDetailsAppID                           string  `json:"lead_details_app_id"`
			IsBusiness                                 bool    `json:"is_business"`
			ProfessionalConversionSuggestedAccountType int     `json:"professional_conversion_suggested_account_type"`
			AccountType                                int     `json:"account_type"`
			DirectMessaging                            string  `json:"direct_messaging"`
			FbPageCallToActionID                       string  `json:"fb_page_call_to_action_id"`
			InstagramLocationID                        string  `json:"instagram_location_id"`
			AddressStreet                              string  `json:"address_street"`
			BusinessContactMethod                      string  `json:"business_contact_method"`
			CityID                                     string  `json:"city_id"`
			CityName                                   string  `json:"city_name"`
			ContactPhoneNumber                         string  `json:"contact_phone_number"`
			IsProfileAudioCallEnabled                  bool    `json:"is_profile_audio_call_enabled"`
			Latitude                                   float64 `json:"latitude"`
			Longitude                                  float64 `json:"longitude"`
			PublicEmail                                string  `json:"public_email"`
			PublicPhoneCountryCode                     string  `json:"public_phone_country_code"`
			PublicPhoneNumber                          string  `json:"public_phone_number"`
			Zip                                        string  `json:"zip"`
			MutualFollowersCount                       int     `json:"mutual_followers_count"`
			IsShopAdsReconEligible                     bool    `json:"is_shop_ads_recon_eligible"`
			ProfileContext                             string  `json:"profile_context"`
			ProfileContextLinksWithUserIds             []any   `json:"profile_context_links_with_user_ids"`
			ProfileContextFacepileUsers                []any   `json:"profile_context_facepile_users"`
			Pk                                         string  `json:"pk"`
			PkID                                       string  `json:"pk_id"`
			Username                                   string  `json:"username"`
			FullName                                   string  `json:"full_name"`
			IsPrivate                                  bool    `json:"is_private"`
			FollowFrictionType                         int     `json:"follow_friction_type"`
			IsVerified                                 bool    `json:"is_verified"`
			ProfilePicID                               string  `json:"profile_pic_id"`
			ProfilePicURL                              string  `json:"profile_pic_url"`
			CurrentCatalogID                           any     `json:"current_catalog_id"`
			MiniShopSellerOnboardingStatus             any     `json:"mini_shop_seller_onboarding_status"`
			ShoppingPostOnboardNuxType                 any     `json:"shopping_post_onboard_nux_type"`
			AdsIncentiveExpirationDate                 any     `json:"ads_incentive_expiration_date"`
			DisplayedActionButtonPartner               any     `json:"displayed_action_button_partner"`
			SmbDeliveryPartner                         any     `json:"smb_delivery_partner"`
			SmbSupportDeliveryPartner                  any     `json:"smb_support_delivery_partner"`
			DisplayedActionButtonType                  string  `json:"displayed_action_button_type"`
			SmbSupportPartner                          any     `json:"smb_support_partner"`
			IsCallToActionEnabled                      bool    `json:"is_call_to_action_enabled"`
			NumOfAdminedPages                          any     `json:"num_of_admined_pages"`
			Category                                   string  `json:"category"`
			AccountBadges                              []any   `json:"account_badges"`
			RequestContactEnabled                      bool    `json:"request_contact_enabled"`
			RobiFeedbackSource                         any     `json:"robi_feedback_source"`
			IsMemorialized                             bool    `json:"is_memorialized"`
			OpenExternalURLWithInAppBrowser            bool    `json:"open_external_url_with_in_app_browser"`
			HasExclusiveFeedContent                    bool    `json:"has_exclusive_feed_content"`
			HasFanClubSubscriptions                    bool    `json:"has_fan_club_subscriptions"`
			PinnedChannelsInfo                         struct {
				PinnedChannelsList []any `json:"pinned_channels_list"`
				HasPublicChannels  bool  `json:"has_public_channels"`
			} `json:"pinned_channels_info"`
			RemoveMessageEntrypoint          bool `json:"remove_message_entrypoint"`
			ChainingResults                  any  `json:"chaining_results"`
			IsBestie                         bool `json:"is_bestie"`
			ExistingUserAgeCollectionEnabled bool `json:"existing_user_age_collection_enabled"`
			ShowPostInsightsEntryPoint       bool `json:"show_post_insights_entry_point"`
			HasPublicTabThreads              bool `json:"has_public_tab_threads"`
			AutoExpandChaining               bool `json:"auto_expand_chaining"`
			IsNewToInstagram                 bool `json:"is_new_to_instagram"`
			HighlightReshareDisabled         bool `json:"highlight_reshare_disabled"`
			ProfilePicURLSignature           struct {
				Expires   int    `json:"expires"`
				Signature string `json:"signature"`
			} `json:"profile_pic_url_signature"`
		} `json:"user"`
		Status string `json:"status"`
	} `json:"result"`
}
